### ISSUE TITLE
Stylelint: Consider switching to a community-maintained config

### ISSUE THREAD

**Issue by adamkudrna** [lmc-eu/code-quality-tools#24]
Maintaining a [custom config like this](https://github.com/stylelint/stylelint-config-standard/blob/main/index.js) is not easy, especially in the long run.

How about moving to a community-maintained config?

## Benefits

1. Less time spent on dev stack, more time on coding.
2. A well-tested config means less bugs and pitfalls in the config itself.
3. Using something close to a community standard improves interoperability and helps new developers read and understand the code more quickly.

## Proposal

- remove [current default config](https://github.com/lmc-eu/code-quality-tools/blob/main/packages/stylelint-config/index.js)
- add [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) for plain CSS (is it necessary at all?)
- add [stylelint-config-standard-scss](https://github.com/stylelint-scss/stylelint-config-standard-scss) for SCSS
- keep [optional config](https://github.com/lmc-eu/code-quality-tools/blob/main/packages/stylelint-config/optional.js) defining properties order

A quick test in `spirit-web` resulted in this project-specific `.stylelintrc` config:

```json
{
  "extends": [
    "stylelint-config-standard-scss",
    "@lmc-eu/stylelint-config/optional"
  ],
  "rules": {
    "indentation": 4,
    "selector-class-pattern": [
      "^lmc-([A-Z][a-zA-Z0-9]*)((--|__)[a-z0-9]+)*$",
      {
        "message": "Expected class selector to be in format `lmc-MyComponent__element`, `lmc-MyComponent--modifier`"
      }
    ]
  }
}
```

Violated rules were: `indentation` (we had 4 spaces instead of 2), `string-quotes` (single quotes were used instead of double quotes), `scss/dollar-variable-empty-line-before` (blank lines between Sass variable groups needed to be removed), and `selector-class-pattern` (kebab case against our SUIT CSS naming convention). I kept our `indentation`, specified custom `selector-class-pattern`, and gave in to the other rules. But anything may be changed the way we want it.

To be fair, more tests on larger code bases may be necessary to see a bigger picture.

## Extending

If we need more strict rules, our config can be extended as we wish in the future. The point is that most of the settings will already be there.

**Comment by literat** [comment]
Well, good idea. But I see here one problem in case of updates. Because with those community configuration I need to create new version every time one of those community configuration updates. So there is a chain of updates: stylelint-config-standard -> @lmc-eu/stylelint-config -> projects.

And thoose updates should't be needed or wanted. That is my first concern.

I also do not know what is a better way. Try to push community standards to the teams and project or melt project rules on which are developers used to into this config?

The second variant was used for creation of this config because there was plenty of rules on which we all agreed and were created long time ago.

I see here some parallel with eslint configs. There are also "standard" and "recommended" community versions but also company specific like "airbnb" which extends nothing or "strv" which done it same way.

So this is not only question of how to keep config short and clean but in particular how to maintain it and push changes forward.

**Comment by literat** [comment]
This is another point to use what you suggests: https://github.com/lmc-eu/cookie-consent-manager/pull/138
